# Generated by Django 5.2.5 on 2026-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='FakeStore', max_length=100),
        ),
    ]
