# Generated by Django 5.2.5 on 2026-05-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default=''),
        ),
    ]
